[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "X-Requested-With, Content-Type, If-Modified-Since"
    Content-Security-Policy = "upgrade-insecure-requests"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 